spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        testOnBorrow: true
        timeBetweenEvictionRunsMillis: 30000
        url: jdbc:postgresql://localhost:5432/hsm
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create